# Generated by Django 5.1 on 2024-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('numero_casa', models.CharField(max_length=10)),
                ('placa_veiculo', models.CharField(max_length=10)),
                ('hora_chegada', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('hora_autorizacao', models.TimeField()),
                ('nome_morador', models.CharField(max_length=100)),
                ('porteiro_autorizou', models.CharField(max_length=100)),
            ],
        ),
    ]
